"""Initial migration

Revision ID: 5da7542ec96a
Revises: 
Create Date: 2026-04-25 21:23:18.851717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5da7542ec96a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_holds_order_item_id'), table_name='order_holds')
    op.drop_index(op.f('ix_order_holds_status'), table_name='order_holds')
    op.drop_table('order_holds')
    op.drop_index(op.f('ix_plan_items_plan_id'), table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_process_definitions_name'), table_name='process_definitions')
    op.drop_table('process_definitions')
    op.drop_index(op.f('ix_transition_definitions_process_definition_id'), table_name='transition_definitions')
    op.drop_table('transition_definitions')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_receiving_records_order_item_id'), table_name='receiving_records')
    op.drop_table('receiving_records')
    op.drop_index(op.f('ix_task_definitions_process_definition_id'), table_name='task_definitions')
    op.drop_table('task_definitions')
    op.drop_index(op.f('ix_process_instances_process_definition_id'), table_name='process_instances')
    op.drop_index(op.f('ix_process_instances_status'), table_name='process_instances')
    op.drop_table('process_instances')
    op.drop_index(op.f('ix_purchase_orders_order_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_supplier_name'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_procurement_plans_name'), table_name='procurement_plans')
    op.drop_table('procurement_plans')
    op.drop_index(op.f('ix_order_items_model_name'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_task_instances_process_instance_id'), table_name='task_instances')
    op.drop_table('task_instances')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_instances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('process_instance_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_definition_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('assignee', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['process_instance_id'], ['process_instances.id'], name=op.f('task_instances_process_instance_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_definition_id'], ['task_definitions.id'], name=op.f('task_instances_task_definition_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_instances_pkey'))
    )
    op.create_index(op.f('ix_task_instances_process_instance_id'), 'task_instances', ['process_instance_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('specification', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], name=op.f('order_items_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_items_pkey'))
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_model_name'), 'order_items', ['model_name'], unique=False)
    op.create_table('procurement_plans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('planned_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('procurement_plans_pkey'))
    )
    op.create_index(op.f('ix_procurement_plans_name'), 'procurement_plans', ['name'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('supplier_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('expected_delivery_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_orders_pkey'))
    )
    op.create_index(op.f('ix_purchase_orders_supplier_name'), 'purchase_orders', ['supplier_name'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_order_number'), 'purchase_orders', ['order_number'], unique=True)
    op.create_table('process_instances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('process_definition_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('started_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['process_definition_id'], ['process_definitions.id'], name=op.f('process_instances_process_definition_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('process_instances_pkey'))
    )
    op.create_index(op.f('ix_process_instances_status'), 'process_instances', ['status'], unique=False)
    op.create_index(op.f('ix_process_instances_process_definition_id'), 'process_instances', ['process_definition_id'], unique=False)
    op.create_table('task_definitions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('process_definition_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('position_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('position_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['process_definition_id'], ['process_definitions.id'], name=op.f('task_definitions_process_definition_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_definitions_pkey'))
    )
    op.create_index(op.f('ix_task_definitions_process_definition_id'), 'task_definitions', ['process_definition_id'], unique=False)
    op.create_table('receiving_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('received_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('received_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('inspector', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('receiving_records_order_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('receiving_records_pkey'))
    )
    op.create_index(op.f('ix_receiving_records_order_item_id'), 'receiving_records', ['order_item_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('transition_definitions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('process_definition_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['process_definition_id'], ['process_definitions.id'], name=op.f('transition_definitions_process_definition_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_task_id'], ['task_definitions.id'], name=op.f('transition_definitions_source_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_task_id'], ['task_definitions.id'], name=op.f('transition_definitions_target_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transition_definitions_pkey'))
    )
    op.create_index(op.f('ix_transition_definitions_process_definition_id'), 'transition_definitions', ['process_definition_id'], unique=False)
    op.create_table('process_definitions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('process_definitions_pkey'))
    )
    op.create_index(op.f('ix_process_definitions_name'), 'process_definitions', ['name'], unique=False)
    op.create_table('plan_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('equipment_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('specification', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estimated_unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['procurement_plans.id'], name=op.f('plan_items_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_items_pkey'))
    )
    op.create_index(op.f('ix_plan_items_plan_id'), 'plan_items', ['plan_id'], unique=False)
    op.create_table('order_holds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hold_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('held_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('released_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('released_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('order_holds_order_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_holds_pkey'))
    )
    op.create_index(op.f('ix_order_holds_status'), 'order_holds', ['status'], unique=False)
    op.create_index(op.f('ix_order_holds_order_item_id'), 'order_holds', ['order_item_id'], unique=False)
    # ### end Alembic commands ###
